### ISSUE TITLE
Can't delete subscription:

### ISSUE THREAD

**Issue by lukesnowden** [pmill/php-plesk#2]
```cli
Error: Parser error: Request is invalid. Error in line 2: Element 'webspace': This element is not expected. Expected is one of ( server, client, domain, subdomain, dns, db_server, mail, migration, certificate, domain_alias )
```
Plesk Version 12.0.18

any help much appreciated

**Comment by pmill** [comment]
Hello, sorry for the delay, I've just completed a full test using the tests/complete_run.php file on a 12.0.18 Plesk server and it returned no errors. Can you make sure you are using the latest code?

If the problem persists could you show me your code.

**Comment by pmill** [comment]
Actually ignore that, I've just realised I didn't include a test for deleting the subscription in complete_run.php. I'll add one now and test it.

**Comment by lukesnowden** [comment]
I created a namespace for each version that may have altered version or package structure. i.e.

```php
<?php namespace Pmill\Plesk\V1660;

use Pmill\Plesk\BaseRequest;
use Pmill\Plesk\DeleteSubscription as BaseDeleteSubscription;

class DeleteSubscription extends BaseDeleteSubscription
{
    protected $packetVersion = '1.6.6.0';
}
```

added the id to your packet template...

```php
<?php namespace Pmill\Plesk;

class DeleteSubscription extends BaseRequest
{
    public $xml_packet = <<<EOT
<?xml version="1.0"?>
<packet version="{PACKET_VERSION}">
<webspace>
	<del>
		<filter>
			<id>{ID}</id>
		</filter>
	</del>
</webspace>
</packet>
EOT;
...
...
```

added the version in the base request

```php
protected $packetVersion = '1.6.6.0';
```

and then altered the getPacket function

```php
protected function getPacket()
    {
        $packet = $this->xml_packet;

        foreach($this->params AS $key=>$value) {
            if(is_bool($value)) {
            	$value = $value ? 'true' : 'false';
            }
            $packet = str_replace('{'.strtoupper($key).'}', $value, $packet);
        }
        $packet = str_replace( "{PACKET_VERSION}", $this->packetVersion, $packet );

        return $packet;
    }
```

regards

**Comment by pmill** [comment]
What was the reason for changing the version? I tested the original against 12.0.18 and it deleted the subscription successfully.

**Comment by lukesnowden** [comment]
packet version 1.5.2.0 not compatible with 12 (well some still appear to work)


Plesk 7.5.4 for Linux/Unix
1.3.5.1
Plesk 7.5.6 for Windows
1.4.0.0
Plesk 8.0 for Linux/Unix | Plesk 7.6 for Windows
1.4.0.0, 1.4.1.0 (updated)
Plesk 7.6.1 for Windows
1.4.1.1
Plesk 8.0.1 for Linux/Unix
1.4.1.2
Plesk 8.1.0 for Linux/Unix | Plesk 8.1.0 for Windows
1.4.2.0
Plesk 8.1.1 for Linux/Unix | Plesk 8.1.1 for Windows
1.5.0.0
Plesk 8.2 for Linux/Unix | Plesk 8.2 for Windows
1.5.1.0
Plesk 8.3 for Linux/Unix | Plesk 8.3 for Windows
1.5.2.0
Plesk 8.4 for Linux/Unix | Plesk 8.6 for Linux/Unix | Plesk 8.4 for Windows | Plesk 8.6 for Windows
1.5.2.1
Parallels Plesk 9.0.0
1.6.0.0
Parallels Plesk 9.0.1
1.6.0.1
Parallels Plesk 9.0.2
1.6.0.2
Parallels Plesk 10.0
1.6.3.0
Parallels Plesk 10.1
1.6.3.1
Parallels Plesk 10.2
1.6.3.2
Parallels Plesk 10.3
1.6.3.3
Parallels Plesk 10.4
1.6.3.4
Parallels Plesk 11.0
1.6.3.5
Parallels Plesk 11.1.0
1.6.4.0
Parallels Plesk 11.5
1.6.5.0
Parallels Plesk 12.0
1.6.6.0

**Comment by pmill** [comment]
I've checked the API documentation for Plesk 12 and it looks like we don't need the packet version for this anyway (http://download1.parallels.com/Plesk/Doc/en-US/online/plesk-api-rpc/index.htm?fileName=33917.htm). I've removed it and tested and it still worked.

**Comment by lukesnowden** [comment]
found a foot note: 

`Note: Starting from Plesk 12, the version attribute can be omitted. And we strongly recommend that you omit it. In this case, the latest available version will be used. This will help you ensure that your code is operable after switching to a new version of Plesk.`

**Comment by lukesnowden** [comment]
The original problem though being that the packet version was being passed and packet version 1.5.2.0   didn't support deleting subscriptions.

**Comment by pmill** [comment]
Just wondering if you've tried the updated code? Did it delete the subscription successfully?

**Comment by lukesnowden** [comment]
I have not tried yours no, I forked your repo and added in the package version and it worked so left it using the fork.
