### ISSUE TITLE
Deleting Alias Domain

### ISSUE THREAD

**Issue by cr0co** [pmill/php-plesk#25]
hello

when i use the example it comes this error:

`[Thu May 12 13:14:27 2016] [error] [client 91.190.19.133] PHP Fatal error:  Uncaught exception 'pmill\\Plesk\\ApiRequestException' with message 'Error: Incorrect request parameters submitted' in php/plesk/alias/src/pmill/Plesk/BaseRequest.php:31\nStack trace:\n#0 /php/plesk/alias/src/pmill/Plesk/DeleteSiteAlias.php(33): pmill\\Plesk\\BaseRequest->__construct(Array, Array)\n#1 /php/plesk/alias/aliasdel.php(9): pmill\\Plesk\\DeleteSiteAlias->__construct(Array, Array)\n#2 {main}\n  thrown in /php/plesk/alias/src/pmill/Plesk/BaseRequest.php on line 31
`
How to fix this error ?

the example looks like an subdomain
`$params = array(
	'alias'=>'testalias2.example.com',
);`

how to insert a alias domain ? test.com doesnt work.

**Comment by pmill** [comment]
Can you submit your full code please?

**Comment by cr0co** [comment]
its your example to delete alias...

`<?php

require_once("config.php");

$params = array(
	'alias'=>'testalias2.example.com',
);

$request = new \pmill\Plesk\DeleteSiteAlias($config, $params);
$info = $request->process();

var_dump($info);

?>`

**Comment by pmill** [comment]
Ah sorry, the example is wrong, try changing the array key from 'alias' to 'domain'.

**Comment by pmill** [comment]
Hello again, I've updated the code so it now accepts the 'alias' parameter as specified in the example.
