### ISSUE TITLE
List subscriptions, get plan

### ISSUE THREAD

**Issue by RamonSmit** [pmill/php-plesk#26]
First of all, thanks for this awesome module! 

I'm listing my subscriptions at this moment, but I would like to receive the service plan too (or at least the name of the plan). 

Is there any way to do this?

**Comment by pmill** [comment]
Hello, yes I should be able to expose that information, while I'm doing it is there any other information you need from the subscriptions?

**Comment by pmill** [comment]
Hello again, I've just pushed an update that exposes the service plan's guid. I've also updated the GetServicePlan request so it accepts the 'guid' as a filter option.

**Comment by RamonSmit** [comment]
Hey, 

Thanks for your help! I really appreciate this! 
This saved me a few hours of working my ass off. 

For now I don't need extra data, maybe in the future but then I will be here again. 

Thanks & Cheers, 
Ramon

**Comment by RamonSmit** [comment]
@pmill On the other side, I have a plesk 12.5 server for development. Please send me an email for access: 

daltcore@gmail.com
