### ISSUE TITLE
CreateSubscription.php line 65: Trying to get property of non-object

### ISSUE THREAD

**Issue by ghermans** [pmill/php-plesk#40]
When i try to create a new subscription i get the error.

`ErrorException in CreateSubscription.php line 65: Trying to get property of non-object`
![error](https://cloud.githubusercontent.com/assets/1594411/18040402/e22aa8b0-6dad-11e6-9861-1731fb119d02.PNG)

**Comment by pmill** [comment]
I think this is some dodgy error handling on my part, essentially your Plesk server has returned an error and the code that checked for the error didn't work. I've updated that code now, if an error has occured it should be stored in `$request->error`, the actual response from plesk should be in `$request->xml_response`.

**Comment by ghermans** [comment]
i will verify right now, will post feedback when i"m done testing.

**Comment by ghermans** [comment]
Thanks for the update @pmill
