### ISSUE TITLE
UpdateEmailPassword

### ISSUE THREAD

**Issue by beckblurry** [pmill/php-plesk#46]
The API function UpdateEmailPassword : 
$params = array(
	'email'=>'test1365695330@example.com',
	'password'=>'areallylongstringwithsomenumbers2',
);
new \pmill\Plesk\UpdateEmailPassword($config, $params);

Doesn't work with me. Please help anything wrong?
Regards,

**Comment by pmill** [comment]
What's the response you are getting from plesk? You can find it in the xml_response property of your UpdateEmailPassword object.

**Comment by beckblurry** [comment]
I try to display the xml response process in the function processResponse($xml) and the xml response is : 
`SimpleXMLElement Object
(
    [@attributes] => Array
        (
            [version] => 1.6.0.2
        )
        
    [mail] => SimpleXMLElement Object
        (
            [update] => SimpleXMLElement Object
                (
                    [add] => SimpleXMLElement Object
                        (
                            [result] => SimpleXMLElement Object
                                (
                                    [status] => error
                                    [errcode] => 1023
                                    [errtext] => Unable to find password_type node
                                    [mailname] => SimpleXMLElement Object
                                        (
                                            [name] => user1
                                        )
                                )
                        )
                )
        )
)` 

and I try to add and change the xml structure to be like this : 
`$request = <<<EOF
<packet>
  <mail>
    <update>
      <set>
        <filter>
          <site-id>SOME ID</site-id>
          <mailname>
            <name>SOME NAME</name>
            <password>
              <value>SOME VALUE</value>
              <type>NEW PASSWORD</type>
            </password>
          </mailname>
        </filter>
      </set>
    </update>
  </mail>
</packet>
EOF;`

but there's doesn't solved.. please more detail advice,, thanks

**Comment by beckblurry** [comment]
is there any suggestions? please help..

**Comment by pmill** [comment]
According to the Plesk API documentation the acceptable values for the `type` node are **plain** or **crpyt** and the `value` node should be your new password. Although it does say `type` is optional.

Can you attach the actual code you are using, and also tell me what version of Plesk you are running the code against.

**Comment by beckblurry** [comment]
hello pmill.. thanks for your reply,,

The problem has been solved .. Previously, it was because there is a mistake I didn't use the version of the xml code <packet> tag that I post to plesk API. Currently I have given version 1.6.3.0 on the tag <packet> XML code and it works,,

```
<?xml version="1.0"?>
<packet version="1.6.3.0">
    <mail>
        <update>
            <set>
                <filter>
                    <site-id>{SITE-ID}</site-id>
                    <mailname>
                        <name>{USERNAME}</name>
                        <password>
                            <value>{PASSWORD}</value>
                            <type>plain</type>
                        </password>
                    </mailname>
                </filter>
            </set>
        </update>
    </mail>
</packet>
```

Thanks for your help pmill :)

**Comment by ilievsoft** [comment]
Hello pmill,
I downloaded the API yesterday and I had this exact error which should have been fixed after the comment above me by beckblurry. Actually the packet XML code is wrong that you have put in UpdateEmailPassword.php.
You have the following actually : 
<?xml version="1.0"?>
<packet version="1.6.0.2">
    <mail>
        <update>
            <add>
                <filter>
                    <domain_id>{DOMAIN_ID}</domain_id>
                    <mailname>
                        <name>{USERNAME}</name>
                        <password>{PASSWORD}</password>
                    </mailname>
                </filter>
            </add>
        </update>
    </mail>
</packet>

This would not work and it is giving the error again : **Unable to find password_type node**

I ended up fixing it on my own :

<?xml version="1.0"?>
<packet version="1.6.3.0">
    <mail>
        <update>
            <set>
                <filter>
                    <site-id>{DOMAIN_ID}</site-id>
                    <mailname>
                        <name>{USERNAME}</name>
                        <password>
                            <value>{PASSWORD}</value>
                         </password>
                    </mailname>
                </filter>
            </set>
        </update>
    </mail>
</packet>

You don't have to put  <type>plain</type>. Works fine like this. It could return an error if the password is too simple according to plesk security password strength level.

Make sure you commit this please. Thanks.
