### ISSUE TITLE
Special chars used in email password will give XML error

### ISSUE THREAD

**Issue by atrandafir** [pmill/php-plesk#5]
I'm creating a email and I get this error because I use very strong random generated password that uses all kind of chars.

DOMDocument::loadXML(): xmlParseEntityRef: no name in Entity, line: 13

I guess it could be because of some symbols like & < > that break the xml syntax.

By the way thanks very much for this library! :)

**Comment by pmill** [comment]
Hi, this should be fixed in the latest dev-master version, would you be able to give it a test? If successful I'll tag a release.

**Comment by pmill** [comment]
Hi, as it's been over a week since the last message on this issue I'm closing it. If the issue persists please open a new issue.
