### ISSUE TITLE
Plesk

### ISSUE THREAD

**Issue by poxin13** [pmill/php-plesk#7]
I can provide you access to a free Plesk 12.5 server for a while if you'd like to update this. I work in hosting, currently developing against the API for a project.

**Comment by pmill** [comment]
@poxin13 yes that would be great if you wouldn't mind.

**Comment by ghermans** [comment]
@pmill  any updates regarding this?

**Comment by pmill** [comment]
@ghermans not heard back from @poxin13 yet.

**Comment by poxin13** [comment]
Working on that today. Do you have an email or chat program I can contact you over?

**Comment by pmill** [comment]
You can get me on dev.pmill@gmail.com.
