### ISSUE TITLE
No error codes passed in exceptions

### ISSUE THREAD

**Issue by pwwoj** [pmill/php-plesk#8]
It is much easier to process exceptions with integer error codes sent by plesk api. Unfortunately they were missed. I have no time right now to fix it everywhere - I needed just one function/class to work properly. Solution to that problem is to fix checkResponse in all classes derived from BaseRequest. Below is example (with added code in bold):

private function checkResponse(\SimpleXMLElement $response) {
        if ($response->system->status == 'error') {
            throw new ApiRequestException("Error: " . $response->system->errtext**, (int)$response->system->errcode** );
        }
    }

**Comment by pmill** [comment]
Hi, I've added the Plesk error code to the exceptions. The changes are currently in dev-master, can you give them a test and then I'll tag a release.

**Comment by pmill** [comment]
These changes are now in the v0.5.0 release.
