### ISSUE TITLE
Managing Wordpress installations

### ISSUE THREAD

**Issue by ronaldjonkers** [pmill/php-plesk#9]
http://docs.plesk.com/en-US/12.5/api-rpc/reference/managing-wordpress-installations.73591/

The enable-auto-updates operation switches on auto-updates on a WordPress installation.
The disable-auto-updates operation switches off auto-updates on a WordPress installation.
The remove command uninstalls WordPress from a site.
The update-core command updates a WordPress installation.
The clear-cache command checks whether updates are available for the selected WordPress installation.
The activate-plugin command activates the specified plugin on the specified WordPress installation.
The deactivate-plugin command deactivates the specified plugin on the specified WordPress installation.
The uninstall-plugin command removes the specified plugin from the specified WordPress installation.
The update-plugin command updates the specified plugin on the specified WordPress installation.
The install-plugin command installs the specified plugin on the specified WordPress installation.
The activate-theme command activates the specified theme on the specified WordPress installation.
The uninstall-theme command removes the specified theme from the specified WordPress installation.
The update-theme command updates the specified theme on the specified WordPress installation.
The install-theme command installs the specified theme on the specified WordPress installation.
The get-list command retrieves the list of all WordPress installations on a server.
The get-plugin-list command retrieves the list of plugins installed on a WordPress installation.
The get-theme-list command retrieves the list of themes installed on a WordPress installation.
The search-plugins command searches for installed plugins by a plugin name.
The search-themes command searches for installed themes by a theme name.
The get-security-status operation retrieves the security status of the specified WordPress installation.

**Comment by pmill** [comment]
Hello, I've added support for these commands in the dev branch. Would you be able to download that branch and give it a test. If it looks ok.

**Comment by pmill** [comment]
Hello, this functionality is now in v0.5.1
